# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
  - repo: local
    hooks:
      - id: clippy
        name: cargo clippy
        description: Run the Clippy linter on the package.
        entry: cargo clippy
        args: ["--all-features", "--tests", "--"]
        language: system
        types: [rust]
        pass_filenames: false
  - repo: local
    hooks:
      - id: fmt
        name: cargo fmt
        description: Format files with cargo fmt.
        entry: cargo +nightly fmt
        language: system
        types: [rust]
        args: ["--"]
