unstable_features = true
normalize_comments = true
imports_granularity = "Crate"
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
